// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whmcqpdxbodwvjlwjxqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobWNxcGR4Ym9kd3ZqbHdqeHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNTkxNzQsImV4cCI6MjA1NDgzNTE3NH0.DQNDFPfc6B9evkuCJkCitq0xl2cHpphuycmuZJOnobw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);